# Generated by Django 4.0.4 on 2023-01-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=25)),
                ('Cost', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Services',
            },
        ),
    ]
